apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 6
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: fire015/nginx:v1
        ports:
        - containerPort: 80
      - name: app
        image: fire015/app:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: app
  type: NodePort